blank_issues_enabled: false
contact_links:
  - name: Bug
    about: If you find a bug, report from here
    url: https://github.com/ryuta69/dotfiles/issues/new?template=bug.md
  - name: Feature
    about: If you want some feature, report from here
    url: https://github.com/ryuta69/dotfiles/issues/new?template=feature.md
  - name: Suggestion
    about: If you have a suggestion to me, report from here
    url: https://github.com/ryuta69/dotfiles/issues/new?template=suggestion.md
